### ISSUE TITLE
2b1: Metadata Mapping and Transformation tools

### ISSUE THREAD

**Issue by jmcmurry** [cancerDHC/operations#30]
- [x]  #25 create web portal
- [x]  #27 Write release notes
- [x]  #29 Develop terminology services
