### ISSUE TITLE
GitHub Tracker for CCDH / node communication

### ISSUE THREAD

**Issue by keblumhardt** [cancerDHC/operations#61]
Create and operationalize a GitHub tracker for nodes to submit tickets to the CCDH team.
- [ ]  Assign community manager to triage and direct tickets, emails, etc.
- [ ]  Determine workflow for different issues - resources for different types of issues, time to reply, process.
- [ ]  Communicate to nodes.

**Comment by monicacecilia** [comment]
@keblumhardt @nicolevasilevsky @volcs0 
Perhaps we could explore the new GitHub _discussion_ feature as a more welcoming way for the CRDC community to interact with CCDG on GitHub instead of having to join, log in, then open an issue? This does not require an invitation link.

We can learn more at https://docs.github.com/en/free-pro-team@latest/discussions

Here's a 60 second introduction to GitHub Discussions: https://youtu.be/DbTWBP3_RbM

(h/t @balhoff)

**Comment by nicolevasilevsky** [comment]
great idea!

**Comment by nicolevasilevsky** [comment]
Could we assign @keblumhardt as the community manager?

**Comment by monicacecilia** [comment]
@keblumhardt - I think we can replace the last point in my list from 30-March with the following. 
- [x] Communicate this workflow on the Support and Engagement Plan.
- [ ] ~~Communicate this information to the nodes: via email, on CRDC website - forward-facing page about our Community building processes. Here would be a good place to add this information (but we may choose to create another page if appropriate): https://harmonization.datacommons.cancer.gov/support~~

And in this way, this ticket is now complete. Do you agree? :bowtie: 

@volcs0 @mellybelly 👀 ⬆️

**Comment by monicacecilia** [comment]
:bowtie:
