### ISSUE TITLE
1c1: Evaluate overlaps in the Wave 1 models, submodel consistency, and domain specific components

### ISSUE THREAD

**Issue by jmcmurry** [cancerDHC/operations#9]
Description: This task aims to define the highest priority data model components that are in common across multiple or all nodes and their relationships to one another. This will define the core draft CRDC-H model. A second component of this task is to examine the submodel consistency across each node's model; e.g. for a given element, what are the discrepancies, inconsistencies, or gaps within each node. 

Within the model alignment spreadsheet [TO BE LINKED]

- [x] gather and document existing models, ontologies used, data element definitions #41  #42 
- [x] document in-common data model components and their relationships #43 
- [x] document representative example data (where available) #45 
- [ ] document discrepancies, inconsistencies, or gaps within each node #44 

Due month 6

**Comment by jmcmurry** [comment]
From [proposal](https://docs.google.com/document/d/14M5sbM4R_KoMq9v0kNsCYdbWz6pj2OFR7ouMhHZcL7Y/edit#): "We will evaluate overlaps in the models, submodel consistency, and domain specific components, identifying the lowest common denominator and prioritizing harmonization work based on common needs. We will gather and review existing models, documentation, ontologies, data element definitions and representative example data sets. "

**Comment by nicolevasilevsky** [comment]
See the Data Model Harmonization February 2020 Progress Report and presentation here:
[Report](https://drive.google.com/file/d/19i0LsyUegA9VRaSj-7ymuo76djGU9qQ0/view?usp=sharing)
[Slide deck](https://docs.google.com/presentation/d/1IE3h-OQTN2Rp8LqNtRwbnZHZlaqa9VxU6pW-kQBGKdU/edit?usp=sharing)
[Video](https://media.oregonstate.edu/media/1_eroxzdna)
